## interdemediate stuff with numpy

In [1]:
import numpy as np

In [2]:
myArray = np.arange(10,21)

In [3]:
myArray

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
myArray[0]

10

In [5]:
myArray[1:4]

array([11, 12, 13])

In [6]:
myArray[:4]

array([10, 11, 12, 13])

In [7]:
myArray[4:]

array([14, 15, 16, 17, 18, 19, 20])

In [8]:
partArray = myArray[:4]

In [9]:
partArray

array([10, 11, 12, 13])

In [10]:
partArray[:] = 50

In [11]:
partArray

array([50, 50, 50, 50])

<p> all array elements become same element </p>

In [12]:
myArray

array([50, 50, 50, 50, 14, 15, 16, 17, 18, 19, 20])

<p> how come myArray also changed </p>

<p> numpy does not send a copy, it is directly effected to save memory </p>

<p> numpy is not sending the copy of this array, it is directly sending the reference of the array, so any changes made to this variable , effects the original array, since we got a reference </p>

In [16]:
copyArray = myArray.copy()

In [17]:
copyArray

array([50, 50, 50, 50, 14, 15, 16, 17, 18, 19, 20])

In [18]:
copyArray[:] = 32

In [19]:
copyArray

array([32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32])

In [20]:
myArray

array([50, 50, 50, 50, 14, 15, 16, 17, 18, 19, 20])

## video 2 numpy 2D selection

In [22]:
myTwoDarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [23]:
myTwoDarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
myTwoDarray[2][1]

8

In [25]:
myTwoDarray[2,1]

8

In [26]:
myTwoDarray[2]

array([7, 8, 9])

<p> slicing of matrix or sub-matrix </p>

In [27]:
myTwoDarray[:2,1:]

array([[2, 3],
       [5, 6]])

<p> :2 from starting row to 2nd row, and then , 1: , from 1st column to last column </p>

In [28]:
myTwoDarray[:1,:1]

array([[1]])

In [29]:
myTwoDarray[:2,1:3]

array([[2, 3],
       [5, 6]])

In [30]:
myTwoDarray[:2,:2]

array([[1, 2],
       [4, 5]])

<p> 0th row to 1st row and 0th column to 2nd column </p>

In [33]:
myTwoDarray[1:3,:2]

array([[4, 5],
       [7, 8]])

<p> from 1st row to 2nd row and then from 0th column to 1st column </p>

In [34]:
myTwoDarray[1:3,1:3]

array([[5, 6],
       [8, 9]])

## video 3 Numpy conditional returns

In [35]:
newArray = np.arange(2,20)

In [36]:
newArray

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [37]:
newArray[newArray > 10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

<p> gives me sub-list that is greater than 10 </p>

In [39]:
newArray > 10

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

<p> in our array which values are greater than 10, gives us result in boolean form </p>

In [40]:
newArray[newArray < 10]

array([2, 3, 4, 5, 6, 7, 8, 9])

## video4 mean deviation , 2c dot and cross products

In [41]:
newArray * 2

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
       38])

<p> multiplying all array elements by 2 </p>

In [42]:
newArray + newArray

array([ 4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36,
       38])

<p> adding array elements with array elements from another array </p>

In [43]:
np.sqrt(newArray)

array([1.41421356, 1.73205081, 2.        , 2.23606798, 2.44948974,
       2.64575131, 2.82842712, 3.        , 3.16227766, 3.31662479,
       3.46410162, 3.60555128, 3.74165739, 3.87298335, 4.        ,
       4.12310563, 4.24264069, 4.35889894])

<p> performing square root on all array elements </p>