In [1]:
import numpy as np

# lesson on numpy

In [2]:
mylist = [74,14,25,32,52]

In [3]:
import numpy as np

In [6]:
myOneDArray = np.array(mylist)

In [7]:
myOneDArray

array([74, 14, 25, 32, 52])

In [11]:
myMultiList = [[14,74,85,312,78],[7,2,145,41,25],[96,12,4,85,32]]

In [12]:
myMultiList

[[14, 74, 85, 312, 78], [7, 2, 145, 41, 25], [96, 12, 4, 85, 32]]

In [13]:
myTwoDArray = np.array(myMultiList)

In [14]:
myTwoDArray

array([[ 14,  74,  85, 312,  78],
       [  7,   2, 145,  41,  25],
       [ 96,  12,   4,  85,  32]])

In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [17]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## get a matrix of all one's 3 * 4

In [19]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.ones((3,4),dtype = int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [21]:
# https://www.educative.io/answers/what-is-the-numpyzeros-function-in-python

In [22]:
np.linspace(0,5,15)

array([0.        , 0.35714286, 0.71428571, 1.07142857, 1.42857143,
       1.78571429, 2.14285714, 2.5       , 2.85714286, 3.21428571,
       3.57142857, 3.92857143, 4.28571429, 4.64285714, 5.        ])

<p> if you plot the above points on a graph they are equally spaced, later we will try it on matplot lib </p>

In [23]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.identity(4,dtype = int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

<p> linear distribution, uniform distribution, normal distribution </p>

In [25]:
np.random.rand(5)

array([0.68661796, 0.44998645, 0.27183691, 0.42133488, 0.64175146])

<p> this is uniform distribution </p>

In [26]:
np.random.rand(5,5)

array([[0.02113862, 0.15553714, 0.33649455, 0.31281308, 0.16707649],
       [0.86967557, 0.82113325, 0.46809807, 0.51202519, 0.65023205],
       [0.1708    , 0.29715055, 0.19521852, 0.66606411, 0.22571693],
       [0.09723844, 0.35833561, 0.85118936, 0.16527573, 0.30978842],
       [0.97847237, 0.88084721, 0.64547636, 0.90396371, 0.32746633]])

In [27]:
np.random.randn(5)

array([-0.44949997,  0.43007841,  1.74038104,  1.05183319, -0.8604015 ])

<p> this is normal distribution </p>

In [28]:
np.random.randn(5,5)

array([[-0.59305498, -0.7993119 ,  0.15599137, -0.72016029, -1.39769086],
       [ 0.40374503, -0.53479443,  0.58340627,  0.19969145, -1.42407011],
       [-1.65731469,  0.5786467 , -1.93142751,  0.3643592 ,  0.71935129],
       [-1.05162284, -0.22497038, -0.01350736,  1.09119599,  0.12434489],
       [ 0.93052809, -1.60174549,  2.53857207,  0.95544828,  2.47814521]])

In [29]:
np.random.randint(1,50)

29

In [30]:
np.random.randint(1,50)

10

<p> get one random integer between this range </p>

In [31]:
myNum = np.arange(25)

In [32]:
myNum

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

<p> you would get a list upto the range 25 </p>

<p> now if i want to reshape the list into a 2-D array, how would i do it </p>

In [37]:
myReshape = myNum.reshape(5,5)

In [38]:
myReshape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
myNum.reshape(4,4)

ValueError: cannot reshape array of size 25 into shape (4,4)

<p> because 4 * 4 is not equal to 25 </p>

In [41]:
myNum.reshape(6,6)

ValueError: cannot reshape array of size 25 into shape (6,6)

In [42]:
myNum.dtype

dtype('int32')

In [43]:
pwd

'C:\\Users\\akhil'

##gives you present working directory