In [1]:
import numpy as np

# lesson on numpy

In [2]:
mylist = [74,14,25,32,52]

In [3]:
import numpy as np

In [6]:
myOneDArray = np.array(mylist)

In [7]:
myOneDArray

array([74, 14, 25, 32, 52])

In [11]:
myMultiList = [[14,74,85,312,78],[7,2,145,41,25],[96,12,4,85,32]]

In [12]:
myMultiList

[[14, 74, 85, 312, 78], [7, 2, 145, 41, 25], [96, 12, 4, 85, 32]]

In [13]:
myTwoDArray = np.array(myMultiList)

In [14]:
myTwoDArray

array([[ 14,  74,  85, 312,  78],
       [  7,   2, 145,  41,  25],
       [ 96,  12,   4,  85,  32]])

In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(0,100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [17]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])